### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/SteamControllerTest#11]
Not sure where I placed my initial post so I will post something here. It has been a while but I need to look back into finally creating some sort of installer for this app and others. My initial choices for installer frameworks were Inno Setup, NSIS, and Qt Installer Framework. I used WiX Toolset in the past but I do not think I would choose that framework again.

Inno Setup does not seem to be able to do what I want and scripting is not that easy; I cannot figure out how to specify optional uninstall components. Qt Installer Framework is very bulky and not well supported. Looking into NSIS now and it seems to mostly do what I would want and the scripting language seems to be fairly easy to read.

The biggest issue is that there needs to be a way in the installer to skip the installing of drivers if they are already installed; there also needs to be an option in the uninstaller to be able to skip uninstalling drivers in case other apps are using said drivers. Additional app(s) will likely have to be included for probing for drivers on the system and sending appropriate codes back to the installer so it can set backend variables accordingly. Later on, an app upgrade path would have to be figured out.

**Comment by Ryochan7** [comment]
Been at this task again. I got a small installer made with NSIS that does pretty much everything that I wanted. Currently trying to make a similar installer using WiX Toolset but I cannot make it do everything that was possible using NSIS. The big problem now is trying to offer the option to call the extra setup programs at the Uninstall step to allow the removal of ViGEmBus, HidHide, or FakerInput. Also, I ended up having to resort to use C# Custom Actions in order to get some tasks done with WiX which is something I originally did not want to do.

**Comment by Ryochan7** [comment]
I'm not going to spend more time on this right now. Here is my progress. Not sure which installer system I will possibly use in the future.

SteamControllerTest_installer.exe (NSIS)
https://drive.google.com/file/d/1v6s2MGen53k2RL_J3ZmhKHiTNhGqTVwp/view?usp=sharing

SteamControllerTest_SetupProject.msi (WiX)
https://drive.google.com/file/d/1FonUNLBGnhPSHFoQMz3L6xrZ-gCGdhux/view?usp=sharing

SteamControllerTest_NSIS_files_20230506.7z
https://drive.google.com/file/d/1wvgZqbMP_lrOD-CWYKeNh3Tlum0ht8Ld/view?usp=sharing

WixSteamControllerSource_20230506.7z
https://drive.google.com/file/d/1q2xH5O-hiZKZO3dCREdFRYe8GnJdYDqB/view?usp=sharing

**Comment by Ryochan7** [comment]
Packaged a new release and used NSIS for making a small installer. Better than nothing I guess. I'll wait a bit before closing this issue.

https://github.com/Ryochan7/SteamControllerTest/releases/tag/v0.0.14

**Comment by axm2** [comment]
I think your installer is not correctly detecting the .NET runtime installation. I had version [6.0.16](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x64-installer) installed, but even after a restart, the installer still sent me to the .NET download page. I tried using the portable version and it didn't complain about missing the runtime dependency.

**Comment by Ryochan7** [comment]
The installer attempts to read registry values under `HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\dotnet\Setup\InstalledVersions\x64\sharedfx\Microsoft.WindowsDesktop.App` and then perform a string compare using `6.`. The routine will return true if a value is found that matches. Can you run regedit and check if there are values in the registry at that location?

**Comment by axm2** [comment]
I do have those registry values present, however it seems the installer still fails.

![image](https://github.com/Ryochan7/SteamControllerTest/assets/24306299/45acc45d-a2ef-4973-b6e8-bc5a7feadc9b)

**Comment by Ryochan7** [comment]
Are you testing the NSIS based installer (.exe) or the WiX based installer (.msi)? I just double checked the project that creates the MSI version and Visual Studio decided to compile the C# Custom Actions DLL as an x86 assembly despite me telling it to compile as x64. If you tried using the MSI installer then the custom action would be looking at the wrong registry view and that would explain it failing.

**Comment by Ryochan7** [comment]
My dev time has been almost nil lately. Ended up finding out the root problem behind the .NET check failing. It was due to not actually handling temporary executables in NSIS properly; the helper programs were not even being bundled. The installers would not work outside my dev environment. Going to have to make a new mapper release just to fix this problem. Too bad I have not had the time to get some other feature ideas incorporated for a new release.

https://github.com/Ryochan7/DS4Windows/issues/3028
