### ISSUE TITLE
Right touchpad as emulator of right analog doesnt hold on the edge a analog position

### ISSUE THREAD

**Issue by popos123** [Ryochan7/SteamControllerTest#21]
Hi,
like in the title - the emulated right analog doesnt hold position and going back to 0 (center). (On SC-controller emi is working fine)

**Comment by Ryochan7** [comment]
Which transform type are you using? Joystick or Mouse-like Joystick? I would think that both types would work as I usually bind Left Touchpad to Joystick and Right Touchpad to Mouse-like Joystick while emulating an Xbox 360 controller. Either way, it seems like the mapper may be no longer detecting the Touchpad press while on the edge of the right touchpad.

**Comment by popos123** [comment]
I'm using default - TouchMouseJoystickAction, but when I want to change this option the program is crashing ....

Could you provide a profil file with configured right analog, that it will works like analog stick?

**Comment by Dont-Know-Nothing** [comment]
My right touchpad, with Transform Type "Joystick" is working fine. Setting it to Mouse-like Joystick doesn't hold position

**Comment by popos123** [comment]
Yeah, exactly. So still is crashing when I try to edit the settings. Could you provide a .Jason file of your profile?

**Comment by Dont-Know-Nothing** [comment]
> Yeah, exactly. So still is crashing when I try to edit the settings. Could you provide a .Jason file of your profile?

Do you want one with the right touchpad set as Transform Type = Joystick with output Right stick?

**Comment by Dont-Know-Nothing** [comment]
> > Do you want one with the right touchpad set as Transform Type = Joystick with output Right stick?
> 
> Yes, I do.

[XInput.json](https://github.com/Ryochan7/SteamControllerTest/files/13078911/XInput.json)

**Comment by Dont-Know-Nothing** [comment]
> > > > Do you want one with the right touchpad set as Transform Type = Joystick with output Right stick?
> > > 
> > > 
> > > Yes, I do.
> > 
> > 
> > [XInput.json](https://github.com/Ryochan7/SteamControllerTest/files/13078911/XInput.json)
> 
> Working perfectly well. Do you have a fixed in the same way a file XInput_TouchDpad.json?

You can download all .json cinfiguration files from the example_files folder on this project code.

**Comment by popos123** [comment]
OK, i was fixed this.
So for people witch the same problem:
1. Delete files in: C:\Users\popos\AppData\Roaming\SCTest\
2. copy "XInput_fix.json" and "XInput_TouchDpad_fix.json" to the folder C:\Users\popos\AppData\Roaming\SCTest\Profiles\SteamController\
[XInput_fix.json](https://github.com/Ryochan7/SteamControllerTest/files/13079420/XInput_fix.json)
[XInput_TouchDpad_fix.json](https://github.com/Ryochan7/SteamControllerTest/files/13079421/XInput_TouchDpad_fix.json)

**Comment by Ryochan7** [comment]
Cool. Glad you got the issue resolved.

Not sure which version you are using. Do you still have the log file from when the application crashed? The file should be located somewhere in `%APPDATA\SCTest\Logs`. The last major change I remember making when it came to property setting was with version 0.0.16 when some tweaks were done regarding Action Layer action ids.

It is too bad I have not had the time to tweak this mapper lately. I have not had time to do much over the past few months.

**Comment by popos123** [comment]
> Cool. Glad you got the issue resolved.
> 
> Not sure which version you are using. Do you still have the log file from when the application crashed? The file should be located somewhere in `%APPDATA\SCTest\Logs`. The last major change I remember making when it came to property setting was with version 0.0.16 when some tweaks were done regarding Action Layer action ids.
> 
> It is too bad I have not had the time to tweak this mapper lately. I have not had time to do much over the past few months.

Yeah, I have a log files (and yes, it was 0.0.16).
[sctest_log_20231023.20.txt](https://github.com/Ryochan7/SteamControllerTest/files/13115327/sctest_log_20231023.20.txt)
[sctest_log_20231023.21.txt](https://github.com/Ryochan7/SteamControllerTest/files/13115328/sctest_log_20231023.21.txt)
[sctest_log_20231023.22.txt](https://github.com/Ryochan7/SteamControllerTest/files/13115329/sctest_log_20231023.22.txt)
[sctest_log_20231023.23.txt](https://github.com/Ryochan7/SteamControllerTest/files/13115330/sctest_log_20231023.23.txt)
[sctest_log.txt](https://github.com/Ryochan7/SteamControllerTest/files/13115331/sctest_log.txt)
[sctest_log_20231023.17.txt](https://github.com/Ryochan7/SteamControllerTest/files/13115332/sctest_log_20231023.17.txt)
[sctest_log_20231023.18.txt](https://github.com/Ryochan7/SteamControllerTest/files/13115333/sctest_log_20231023.18.txt)
[sctest_log_20231023.19.txt](https://github.com/Ryochan7/SteamControllerTest/files/13115335/sctest_log_20231023.19.txt)

**Comment by Ryochan7** [comment]
Okay. I need to change how the thread events are handled in the ViewModels. The events depend on the input thread loop so it depends on input packets coming from the controller. I am going to assume you are probably connected via BLE as the Steam Controller would stop sending input events after a period of inactivity. With no input events, the lock will just get stuck waiting for the input thread to call the mapper where the requested event would be processed. The UI would just hang.

Picking up the controller should be enough to get the Steam Controller to send Gyro data and get the UI working again. Kind of annoying.
