### ISSUE TITLE
Force Center touch for TouchpadStickAction

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/SteamControllerTest#23]
Wanting to make a note for future reference. Ever since Steam Input added a new version of Joystick Centering mode for the Touchpad Joystick mapping, I have been meaning to add something similar but a bit more simplified here. That was months ago that I intended to work on it. Finally got around to it with commit f74580fa7a07298346d8befa60a06e024e835b0a.

The logic is fairly simple. Joystick output will not activate for a Touchpad Touch until the assigned dead zone has been touched. Not sure if I will end up using this option anywhere or not. Also, the state will not transfer if the action has overridden properties in another Action Layer. I need to look at some other actions and remind myself how I handled state variable transfer on an Action Layer change in cases like this.

**Comment by Dont-Know-Nothing** [comment]
This is great! Now mapping directional input and Dpad on the same touchpad is posible (using action layer)
