### ISSUE TITLE
Project EOL sometime soon. No definite date

### ISSUE THREAD

**Issue by Ryochan7** [Ryochan7/SteamControllerTest#27]
There is pretty much no path forward for this project. I am ending my support for several of my current projects including this one. There will be one small patch release put out there before I decide to close this repository. There is no timetable for when I plan to close this repo other than soon.

**Comment by Dont-Know-Nothing** [comment]
Sad to hear this project is EOL. I guess nobody is using a SC anymore. Thanks for all your effort put in this and Ds4windows, Have a good 2024!

**Comment by Ryochan7** [comment]
At some point, I would have liked to add Steam Controller support into DS4MapperTest and re-brand that project. Both code bases use almost the same code base but the main mapper class in this project behaves a bit differently. The conversion would likely be doable. Maybe I will attempt it before closing that project as well.

The main reason for quitting is a lack of a supported controller emulation driver. Thanks to driver publishing policy changes by Microsoft over the past few years, driver development on Windows is behind a pretty expensive paywall; IIRC it is around $500 per year plus I would need to run an officially registered business (likely an LLC). The last time I had access to that type of money was from government stimulus checks during Corona.

There are other factors and I do not feel like I have the time anymore to put my time into a project just to experiment and learn. If I am not being compensated for my time or it does not lead to future employment opportunities than it is not worth the effort.

**Comment by Dont-Know-Nothing** [comment]
It would be great if you add support for the Steam Controller to DSMapperTest but totally understand you, i don't think people in general realizes the time and effort guys like you put into apps and software we use everyday. In my particular case, exchange rates and monetary restrictions in my country (Argentina), makes donation almost impossible.

Again! have a great year! and I hope you receive the recognition you deserve for all your projects.

P.S. I can't find any link to a Paypal account or something like that to try to make a donation.

**Comment by Ryochan7** [comment]
It still needs to be tweaked but I finally got Steam Controller support migrated; it only took about two hours. For now, Bluetooth support has not been enabled. Hopefully getting BLE working will just require enabling the check in the DeviceEnumerator and testing it.

https://github.com/Ryochan7/DS4MapperTest/issues/20

https://github.com/Ryochan7/DS4MapperTest/commit/76a2d8c6cea28d3a55ef05267fa4f89e9b7554a5

**Comment by Dont-Know-Nothing** [comment]
Hi! First of all, can't believe you add this in 2 hours! Second I'm dumb!, cloned the repository, updated VS to 17.8, start debugging and lots of Vigembus and Fakerinput errors. Removed and added both project references with .dll on the libs folder and then...  System.DllNotFoundException: 'Unable to load DLL 'FakerInputDll.dll'. 
I was just to comment and I realize I was debugging wit any cpu setting, Changed to x64 and everything was fine!.
Just tested, Mouse like Joystick working on the gyro Awesome!

**Comment by Ryochan7** [comment]
I think I am going to close this repo towards the end of January. There are likely some more fixes I should make before closing this project. This repo is pretty much deprecated now that Steam Controller support works in the DS4MapperTest mapper. Even that repo will not last too much longer (sometime in February maybe). Although messing around with this mapper code is still a bit of fun, it will not lead to anything long term.

**Comment by Ryochan7** [comment]
> Hi! First of all, can't believe you add this in 2 hours! Second I'm dumb!, cloned the repository, updated VS to 17.8, start debugging and lots of Vigembus and Fakerinput errors. Removed and added both project references with .dll on the libs folder and then... System.DllNotFoundException: 'Unable to load DLL 'FakerInputDll.dll'. I was just to comment and I realize I was debugging wit any cpu setting, Changed to x64 and everything was fine!. Just tested, Mouse like Joystick working on the gyro Awesome!

I should remove any trace of the AnyCPU platform target from the project file. Even though the default platform set in the project file is set to x64, VS will sometimes ignore that setting and just try to force AnyCPU when first opening a project anyway; MSBuild would honor the default setting when run on its own though. As you have experienced, some required DLL files will not be included if AnyCPU is used for the platform target.

**Comment by Ryochan7** [comment]
I think I'm done.
